create table time (id int8 generated by default as identity, nome varchar(255), idade numeric(19, 2), time varchar(255), primary key (id));
INSERT INTO produto(nome, idade, time) VALUES('Doncic', 23, Mavs);
INSERT INTO produto(nome, idade, time) VALUES('Morant', 21, Grizlies);
INSERT INTO produto(nome, idade, time) VALUES('DeRozan', 32, Bulls);
INSERT INTO produto(nome, idade, time) VALUES('Lavine', 28, Bulls);
